const Studentclassesdetailscard = [
    {
        category: "Scheduled",
        image: "images/DayangHapsah.png",
        name: "Dayang Hapsah",
        price: "$150",
        time: "2 hrs Ago",
        subject: "English Literature Physics",
        level: "A-level",
        classtype: "Scheduled - 01 Sept'22  I  9am - 10am",
        cancel: "Cancel",
        workstation: "Workstation",
        rateyourexperience: "Rate your Experience",
        comment: "images/chat-icon-box.png",
        cancelledclasses: "cancelledclasses",
        ejectacceptbutton: "ejectacceptbutton",
        rating: "rating",
        Panding: "Pending",
        subjectclasstype: "subjectclasstype",
    },

    {
        category: "Scheduled",
        image: "images/Zoemalik.png",
        name: "Zoe malik",
        price: "20",
        time: "4:52 mins Left",
        subject: "Mathematics",
        level: "A-level",
        classtype: "Scheduled - 01 Sept'22  I  9am - 10am",
        cancel: "Cancel",
        workstation: "Workstation",
        comment: "images/chat-icon-box.png",
        cancelledclasses: "cancelledclasses",
        rateyourexperience: "Rate your Experience",
        ejectacceptbutton: "ejectacceptbutton",
        rating: "rating",
        Accepted: "Accepted",
        subjectclasstype: "subjectclasstype",
    },

    {
        category: "ProblemSolving",
        image: "images/EllenaWilkinson.png",
        name: "Ellena Wilkinson",
        price: "$20",
        time: "4:52 mins Left",
        subject: "Mathematics",
        level: "A-level",
        classtype: "Problem Solving",
        cancel: "Cancel",
        viewdetail: "View Detail",
        comment: "images/chat-icon-box.png",
        cancelledclasses: "cancelledclasses",
        ejectacceptbutton: "ejectacceptbutton",
        rateyourexperience: "Rate your Experience",
        RatingPending: "Rating Pending",
        Accepted: "Accepted",
        subjectclasstype: "subjectclasstype",
    },

    {
        category: "ProblemSolving",
        image: "images/MilesHowardLuck.png",
        name: "Miles Howard Luck",
        price: "$15",
        time: "4:52 mins Left",
        subject: "Mathematics",
        level: "A-level",
        classtype: "Problem Solving",
        cancel: "Cancel",
        viewdetail: "View Detail",
        comment: "images/chat-icon-box.png",
        cancelledclasses: "cancelledclasses",
        ejectacceptbutton: "ejectacceptbutton",
        rateyourexperience: "Rate your Experience",
        RatingPending: "Rating Pending",
        Rejected: "Rejected",
        subjectclasstype: "subjectclasstype",
    },

    {
        category: "GroupClasses",
        image: "images/Groupclasses1.png",
        name: "Did you make your New Year resolutions?",
        price: "$50",
        time: "4:52 mins Left",
        subject: "English Literature Physics",
        level: "A-level",
        classtype: "Group Classes",
        cancel: "Cancel",
        workstation: "Workstation",
        groupclassbox:"groupclassbox",
        cancelledclasses: "cancelledclasses",
        subjectclasstypelevel: "subjectclasstypelevel",
    },

    {
        category: "GroupClasses",
        image: "images/Groupclasses22.png",
        name: "IELTS Speaking for Academic & General...",
        price: "$50",
        time: "4:52 mins Left",
        subject: "English Literature Physics",
        level: "A-level",
        classtype: "Group Classes",
        cancel: "Cancel",
        workstation: "Workstation",
        groupclassbox:"groupclassbox",
        cancelledclasses: "cancelledclasses",
        subjectclasstypelevel: "subjectclasstypelevel",
    },

];

export default Studentclassesdetailscard