export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const IS_LOADING = "IS_LOADING";
export const AUTH_LOADING = "AUTH_LOADING";
export const IS_PROFILE_LOADING = "IS_PROFILE_LOADING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const USERLIST_SUCCESS = "USERLIST_SUCCESS";

export const PAGE_LIST_SUCCESS = "PAGE_LIST_SUCCESS";

//------------------------------------------------common-API's---------------------------------------------------------------

export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_ERROR = "RESEND_OTP_ERROR"


//------------------------------------------------instructor-auth---------------------------------------------------------------

export const INSTRUCTOR_LOGIN_SUCCESS = "INSTRUCTOR_LOGIN_SUCCESS";
export const INSTRUCTOR_LOGIN_ERROR = "INSTRUCTOR_LOGIN_ERROR";

export const INSTRUCTOR_REGISTER_SUCCESS = "INSTRUCTOR_REGISTER_SUCCESS";
export const INSTRUCTOR_REGISTER_ERROR = "INSTRUCTOR_REGISTER_ERROR";

export const INSTRUCTOR_SOCIAL_LOGIN_SUCCESSFULL = "INSTRUCTOR_SOCIAL_LOGIN_SUCCESSFULL";
export const INSTRUCTOR_SOCIAL_LOGIN_ERROR = "INSTRUCTOR_SOCIAL_LOGIN_ERROR";

//------------------------------------------------instructor-completeProfile---------------------------------------------------------------

export const GET_CLASS_LEVEL_INSTRUCTOR_SUCCESS = "GET_CLASS_LEVEL_INSTRUCTOR_SUCCESS";
export const GET_CLASS_LEVEL_INSTRUCTOR_ERROR = "GET_CLASS_LEVEL_INSTRUCTOR_ERROR";

export const GET_QUALIFICATION_LEVEL_INSTRUCTOR_SUCCESS = "GET_QUALIFICATION_LEVEL_INSTRUCTOR_SUCCESS";
export const GET_QUALIFICATION_LEVEL_INSTRUCTOR_ERROR = "GET_QUALIFICATION_LEVEL_INSTRUCTOR_ERROR";

export const GET_GRADE_INSTRUCTOR_SUCCESS = "GET_GRADE_INSTRUCTOR_SUCCESS";
export const GET_GRADE_INSTRUCTOR_ERROR = "GET_GRADE_INSTRUCTOR_ERROR";

export const GET_TAGS_INSTRUCTOR_SUCCESS = "GET_TAGS_INSTRUCTOR_SUCCESS";
export const GET_TAGS_INSTRUCTOR_ERROR = "GET_TAGS_INSTRUCTOR_ERROR";

//------------------------------------------------ instructor Complete Profile ---------------------------------------------------------------
export const SUCCESS_COMPLETE_PROFILE_PERSONAL_DETAILS = "SUCCESS_COMPLETE_PROFILE_PERSONAL_DETAILS";
export const ERROR_COMPLETE_PROFILE_PERSONAL_DETAILS = "ERROR_COMPLETE_PROFILE_PERSONAL_DETAILS";

export const SUCCESS_COMPLETE_PROFILE_QUALIFICATIONS = "SUCCESS_COMPLETE_PROFILE_QUALIFICATIONS";
export const ERROR_COMPLETE_PROFILE_QUALIFICATIONS = "ERROR_COMPLETE_PROFILE_QUALIFICATIONS";

export const SUCCESS_COMPLETE_PROFILE_TEACHING_DETAILS = "SUCCESS_COMPLETE_PROFILE_TEACHING_DETAILS";
export const ERROR_COMPLETE_PROFILE_TEACHING_DETAILS = "ERROR_COMPLETE_PROFILE_TEACHING_DETAILS";

export const SUCCESS_COMPLETE_PROFILE_AVAILABILITY = "SUCCESS_COMPLETE_PROFILE_AVAILABILITY";
export const ERROR_COMPLETE_PROFILE_AVAILABILITY = "ERROR_COMPLETE_PROFILE_AVAILABILITY";

export const SUCCESS_COMPLETE_PROFILE_BANK_DETAILS = "SUCCESS_COMPLETE_PROFILE_BANK_DETAILS";
export const ERROR_COMPLETE_PROFILE_BANK_DETAILS = "ERROR_COMPLETE_PROFILE_BANK_DETAILS";

//------------------------------------------------instructor-myprofile-section---------------------------------------------------------------

export const BOOKING_REQUEST_LIST_SUCCESS = "BOOKING_REQUEST_LIST_SUCCESS";
export const BOOKING_REQUEST_LIST_ERROR = "BOOKING_REQUEST_LIST_ERROR";


export const BOOKING_REQUEST_ACCEPT_SUCCESS = "BOOKING_REQUEST_ACCEPT_SUCCESS";
export const BOOKING_REQUEST_ACCEPT_ERROR = "BOOKING_REQUEST_ACCEPT_ERROR";


//-------------------------------------------------instructor-list-api----------------------------------------------------------------------------------------

export const INSTRUCTOR_LIST_SUCCESS = "INSTRUCTOR_LIST_SUCCESS";
export const INSTRUCTOR_LIST_ERROR = "INSTRUCTOR_LIST_ERROR";

export const INSTRUCTOR_DETAIL_SUCCESS = "INSTRUCTOR_DETAIL_SUCCESS";
export const INSTRUCTOR_DETAIL_ERROR = "INSTRUCTOR_DETAIL_ERROR";

export const INSTRUCTOR_LIST_DATA_SUCCESS = "INSTRUCTOR_LIST_DATA_SUCCESS";
export const INSTRUCTOR_LIST_DATA_ERROR = "INSTRUCTOR_LIST_DATA_ERROR";

export const INSTRUCTOR_LEVEL_SUCCESS = "INSTRUCTOR_LEVEL_SUCCESS";
export const INSTRUCTOR_LEVEL_ERROR = "INSTRUCTOR_LEVEL_ERROR";

export const INSTRUCTOR_SUBJECTS_LIST_SUCCESS = "INSTRUCTOR_SUBJECTS_LIST_SUCCESS";
export const INSTRUCTOR_SUBJECTS_LIST_ERROR = "INSTRUCTOR_SUBJECTS_LIST_ERROR";


export const INSTRUCTOR_LEVEL_LIST_SUCCESS = "INSTRUCTOR_LEVEL_LIST_SUCCESS";
export const INSTRUCTOR_LEVEL_LIST_ERROR = "INSTRUCTOR_LEVEL_LIST_ERROR";


export const INSTRUCTOR_PAYMENT_SUCCESS = "INSTRUCTOR_PAYMENT_SUCCESS";
export const INSTRUCTOR_PAYMENT_ERROR = "INSTRUCTOR_PAYMENT_ERROR";

export const INSTRUCTOR_PAYMENT_PROBLEM_SOLVING_SUCCESS = "INSTRUCTOR_PAYMENT_PROBLEM_SOLVING_SUCCESS";
export const INSTRUCTOR_PAYMENT_PROBLEM_SOLVING_ERROR = "INSTRUCTOR_PAYMENT_PROBLEM_SOLVING_ERROR";

export const INSTRUCTOR_PAYMENT_SUBSCRIPTION_SUCCESS = "INSTRUCTOR_PAYMENT_SUBSCRIPTION_SUCCESS";
export const INSTRUCTOR_PAYMENT_SUBSCRIPTION_ERROR = "INSTRUCTOR_PAYMENT_SUBSCRIPTION_ERROR";

export const TUTOR_SUBJECT_SUCCESS = "TUTOR_SUBJECT_SUCCESS";
export const TUTOR_SUBJECT_ERROR = "TUTOR_SUBJECT_ERROR";

export const TUTOR_LANGUAGE_SUCCESS = "TUTOR_LANGUAGE_SUCCESS";
export const TUTOR_LANGUAGE_ERROR = "TUTOR_LANGUAGE_ERROR";

//------------------------------------------------student-auth---------------------------------------------------------------
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_ERROR = "STUDENT_LOGIN_ERROR";

export const FORGOT_EMAIL_SUCCESS = "FORGOT_EMAIL_SUCCESS";
export const FORGOT_EMAIL_ERROR = "FORGOT_EMAIL_ERROR";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_ERROR = "STUDENT_REGISTER_ERROR";

export const OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS";
export const OTP_VERIFICATION_ERROR = "OTP_VERIFICATION_ERROR";

export const STUDENT_SOCIAL_LOGIN_SUCCESSFULL = "STUDENT_SOCIAL_LOGIN_SUCCESSFULL";
export const STUDENT_SOCIAL_LOGIN_ERROR = "STUDENT_SOCIAL_LOGIN_ERROR";


export const INSTRUCTOR_PERSONAL_DETAIL_SUCCESS = "INSTRUCTOR_PERSONAL_DETAIL_SUCCESS";
export const INSTRUCTOR_PERSONAL_DETAIL_ERROR = "INSTRUCTOR_PERSONAL_DETAIL_ERROR";




//----------------------------------------------card-type-------------------------------------------------------

export const CARD_CREATE_SUCCESS = "CARD_CREATE_SUCCESS";
export const CARD_CREATE_ERROR = "CARD_CREATE_ERROR";

export const CARD_LIST_SUCCESS = "CARD_LIST_SUCCESS";
export const CARD_LIST_ERROR = "CARD_LIST_ERROR";

export const CARD_REMOVE_SUCCESS = "CARD_REMOVE_SUCCESS";
export const CARD_REMOVE_ERROR = "CARD_REMOVE_ERROR";

export const PAY_BY_CARD_SUCCESS = "PAY_BY_CARD_SUCCESS";
export const PAY_BY_CARD_ERROR = "PAY_BY_CARD_ERROR";

//------------------------------------------------Group-page----------------------------------------------------------------------------------

export const ADD_GROUP_CLASSES_SUCCESS = "ADD_GROUP_CLASSES_SUCCESS";
export const ADD_GROUP_CLASSES_ERROR = "ADD_GROUP_CLASSES_ERROR";

export const GROUP_CLASSES_LIST_SUCCESS = "GROUP_CLASSES_LIST_SUCCESS";
export const GROUP_CLASSES_LIST_ERROR = "GROUP_CLASSES_LIST_ERROR";


//------------------------------------------------home-page----------------------------------------------------------------------------------

export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_ERROR = "GET_COURSES_ERROR";

export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_ERROR = "GET_BLOGS_ERROR";

export const GET_BLOG_DETAIL_SUCCESS = "GET_BLOG_DETAIL_SUCCESS";
export const GET_BLOG_DETAIL_ERROR = "GET_BLOG_DETAIL_ERROR";



export const GET_BLOGS_CATEGORY_SUCCESS = "GET_BLOGS_CATEGORY_SUCCESS";
export const GET_BLOGS_CATEGORY_ERROR = "GET_BLOGS_CATEGORY_ERROR";

export const GET_FAQ_SUCCESS = "GET_FAQ_SUCCESS";
export const GET_FAQ_ERROR = "GET_FAQ_ERROR";

export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_ERROR = "GET_BANNER_ERROR";

export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";

export const GET_TESTIMONIALSS_SUCCESS = "GET_TESTIMONIALSS_SUCCESS";
export const GET_TESTIMONIALSS_ERROR = "GET_TESTIMONIALSS_ERROR";

export const GET_COUNTRY_LIST_SUCCESS = "GET_COUNTRY_LIST_SUCCESS";
export const GET_COUNTRY_LIST_ERROR = "GET_COUNTRY_LIST_ERROR";

export const POST_STATES_LIST_SUCCESS = "POST_STATES_LIST_SUCCESS";
export const POST_STATES_LIST_ERROR = "POST_STATES_LIST_ERROR";

export const POST_CITIES_LIST_SUCCESS = "POST_CITIES_LIST_SUCCESS";
export const POST_CITIES_LIST_ERROR = "POST_CITIES_LIST_ERROR";

//------------------------------------------------cms-page----------------------------------------------------------------------------------

export const ONDEMAND_COUPON_SUCCESS = "ONDEMAND_COUPON_SUCCESS";
export const ONDEMAND_COUPON_ERROR = "ONDEMAND_COUPON_ERROR";

export const APPLY_COUPON_CODE_SUCCESS = "APPLY_COUPON_CODE_SUCCESS";
export const APPLY_COUPON_CODE_ERROR = "APPLY_COUPON_CODE_ERROR";

export const ONDEMAND_PAYMENT_ZOOMLINK_SUCCESS = "ONDEMAND_PAYMENT_ZOOMLINK_SUCCESS";
export const ONDEMAND_PAYMENT_ZOOMLINK_ERROR = "ONDEMAND_PAYMENT_ZOOMLINK_ERROR";

export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_ERROR = "CONTACT_US_ERROR";

//------------------------------------------------blog-page----------------------------------------------------------------------------------

export const BLOG_ADD_STUDENT_SUCCESS = "BLOG_ADD_STUDENT_SUCCESS";
export const BLOG_ADD_STUDENT_ERROR = "BLOG_ADD_STUDENT_ERROR"; 


export const BLOG_ADD_INSTRUCTOR_SUCCESS = "BLOG_ADD_INSTRUCTOR_SUCCESS";
export const BLOG_ADD_INSTRUCTOR_ERROR = "BLOG_ADD_INSTRUCTOR_ERROR"; 

export const BLOG_LIKE_SUCCESS = "BLOG_LIKE_SUCCESS";
export const BLOG_LIKE_ERROR = "BLOG_LIKE_ERROR"; 
